export const BASE_URL="https://api.themoviedb.org/";
export const API_KEY="d70789f6adbe0108ea7b4cfa61b6c198";
export const NOW_PLAYING="3/movie/now_playing";
export const CAST_CREW="3/movie/{movie_id}/credits";
export const SINGLEMOV_DEL="3/movie/{movie_id}";
export const SIMILAR_MOVIE="3/movie/{movie_id}/similar";
export const MOVIE_TRAILER="3/movie/{movie_id}/videos";
export const TRAILER_LANGUAGE="&language=en-";
export const YOUTUBE_API="https://www.youtube.com/watch?v=";
export const CREDIT_URL="3/credit/"